name: Build & Deploy website to github pages

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Setup Python
        uses: actions/setup-python@v4.4.0
        with:
          python-version: 3.11

      - uses: actions/checkout@v3

      - name: Install Python requirements
        uses: aabadie/action-install-python-requirements@v2.0.1
        with:
          requirements: requirements.txt
          update-pip: true

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.10
        with:
          source: style/sass/style.scss
          destination: style/style.css

      - name: Build
        run: python make.py
